{
 "title": " TAble",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Bar chart ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT by, count() as posts\nFROM trendpulse.hackernews\nGROUP BY by\nORDER BY posts DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Rss news",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT source, count() as articles\nFROM trendpulse.rss_news\nGROUP BY source\nORDER BY articles DESC"
    }
   ]
  },
  {
   "title": "Amount posts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT title, score\nFROM trendpulse.hackernews\nORDER BY score DESC\nLIMIT 10"
    }
   ]
  }
 ]
}